# This file was generated by GoReleaser. DO NOT EDIT.
class Pbgopy < Formula
  desc "Copy and paste between devices"
  homepage "https://github.com/nakabonne/pbgopy"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.2.1/pbgopy_0.2.1_darwin_amd64.tar.gz"
    sha256 "b8fc51d240d1e896516cbcebe88c4e2eef4633cc59ee868b4a1c765cd28f263d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.2.1/pbgopy_0.2.1_linux_amd64.tar.gz"
    sha256 "6e11a07eba4a0108b2f93ef0b150f08a99887357ac5724ba135362315956e10f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.2.1/pbgopy_0.2.1_linux_armv6.tar.gz"
    sha256 "e91cf7b8ba2232fc519277f15aca15ac045486f21130be1772008082dbea5000"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.2.1/pbgopy_0.2.1_linux_arm64.tar.gz"
    sha256 "f7ddadd884627c5befd15b081bc1c4999c505557fef9380a7b313f7e3bf42f2a"
  end

  def install
    bin.install "pbgopy"
  end
end
