# This file was generated by GoReleaser. DO NOT EDIT.
class Pbgopy < Formula
  desc "Copy and paste between devices"
  homepage "https://github.com/nakabonne/pbgopy"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.1.1/pbgopy_0.1.1_darwin_amd64.tar.gz"
    sha256 "4d5b74aec169bce5da699ddf4f3e9578f1b9bcad160162cc67e488b03dbd878d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.1.1/pbgopy_0.1.1_linux_amd64.tar.gz"
    sha256 "b920d4291d0aff322e4353801006efcd4327da42789ba1030f5f5ecbbe793c48"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.1.1/pbgopy_0.1.1_linux_armv6.tar.gz"
    sha256 "319dfc4aec7b74d6bb76c02e3461496ceb675a7aa32f143e0cb671f7dcb47d40"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nakabonne/pbgopy/releases/download/v0.1.1/pbgopy_0.1.1_linux_arm64.tar.gz"
    sha256 "e3fbcb61818f1402be29aa84558bab6b0d3107c76a5bd32a9984ccb77a0d8cd9"
  end

  def install
    bin.install "pbgopy"
  end
end
